services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command:
      - "start:e2e"
    volumes:
      - database_e2e:/home/node/app/database

  frontend:
    build:
      context: ../frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy

  playwright:
    build:
      context: ../frontend
      dockerfile: playwright.Dockerfile
    ports:
      - "8081:9323"
    depends_on:
      frontend:
        condition: service_healthy

volumes:
  database_e2e: