services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - database_e2e:/home/node/app/database
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9428/api/status" ]
      interval: 10s
      timeout: 30s
      retries: 5

  frontend:
    build:
      context: ../frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:4200"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4200/" ]
      interval: 10s
      timeout: 30s
      retries: 5

  playwright:
    build:
      context: ../frontend
      dockerfile: playwright.Dockerfile
    depends_on:
      frontend:
        condition: service_healthy

volumes:
  database_e2e: